"use client"
import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header";
import { Toaster } from "@/components/ui/sonner";
import { usePathname } from "next/navigation";
import { UpdateCartContext } from "./_context/UpdateCartContext";
import { useState } from "react";


const jostFont = localFont({
  src: "./fonts/jost-VF.woff",
  variable: "--font-jost",
  weight: "100 900", // Jost supports variable weights
});

const jostFont1 = localFont({
  src: "./fonts/jost-VF.woff2",
  variable: "--font-jost",
  weight: "100 900",
});

// export const metadata = {
//   title: "E-commerce website",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params = usePathname()
  const [updateCart,setUpdateCart]=useState(false)
  const showHeader =params == "/sign-in" || params =="/sign-up" ? false:true;
  return (
    <html lang="en">
      <body
        className={`${jostFont.variable} ${jostFont1.variable} bg-white text-black antialiased`}
      >
      <UpdateCartContext.Provider value={{updateCart,setUpdateCart}}>

       {showHeader&& <Header/>}
       {children}
        <Toaster />

      </UpdateCartContext.Provider>
      </body>
    </html>
  );
}
